#!/usr/bin/env python3
"""Split the multi-event Boianai source block into individually provenance-linked case candidates.

Narratives are chronological reconstructions of what the archived source reports. They do not
endorse the observations, do not infer missing phases, and do not assign Close Encounter classes.
"""
from __future__ import annotations
import argparse,csv,hashlib,json,shutil,sqlite3
from pathlib import Path

CASES=[
 {'id':'AU-NAA-CASE-BOIANAI-19590621','title':'Boianai — Stephen Moi observation — 21 June 1959','pages':(203,204),'date':'1959-06-21','start':'01:00','observer':'Stephen Moi','location':'Boianai, Territory of Papua and New Guinea','confidence':'HIGH','narrative':"At about 1:00 a.m. on 21 June 1959 at Boianai, teacher Stephen Moi reported seeing a bright white light descending silently from high in the sky from a point about a quarter-mile offshore, slightly west of the station. Over roughly three minutes it moved eastward parallel to the coast while descending, then stopped a little east of the station at an estimated height of about 300 feet. After remaining stationary for about half a minute, it gradually dimmed until Moi said he could distinguish an inverted-saucer form tilted slightly backward, with part of its underside visible and about four dark round marks beneath it. He then reported that the object moved upward and disappeared into cloud. The account was recorded by William B. Gill on 23 June.",'facts':[('EVENT_START','About 1:00 a.m., 21 June 1959'),('INITIAL_OBSERVATION','Bright white light reported descending silently offshore west of Boianai'),('MOTION','Moved eastward parallel to the coast while descending for about three minutes'),('HOVER','Stopped east of the station at an estimated altitude of about 300 feet for about half a minute'),('APPEARANCE','As brightness decreased, observer described an inverted-saucer form with four dark round marks beneath'),('EVENT_END','Object reportedly climbed and disappeared into cloud')]},
 {'id':'AU-NAA-CASE-BOIANAI-19590626','title':'Boianai multi-witness observation — 26 June 1959','pages':(204,207),'date':'1959-06-26','start':'18:45','observer':'William B. Gill and other Boianai witnesses','location':'Boianai, Territory of Papua and New Guinea','confidence':'HIGH','narrative':"On the evening of 26 June 1959 at Boianai, William B. Gill recorded a sequence beginning at about 6:45 p.m. with a bright white light to the northwest. He called other witnesses as the light appeared to approach and descend; the notes describe changing yellow-orange brightness and, beginning around 6:55 p.m., figures that the observers interpreted as people moving on the upper part of the object. The source records repeated appearances and disappearances of these figures and a thin blue light or beam before the principal object passed into cloud at about 7:20 p.m. Later that evening Gill recorded additional objects in several directions, including overhead, over the sea and toward nearby villages, while a larger object remained comparatively stationary. The notes say some objects moved through low cloud and illuminated it. Around 9:05–9:10 p.m. several objects disappeared; the larger object was reported to depart showing red light, reappear, and at about 9:30 move away toward Giwa while changing from white to red and then blue-green. An overhead object was again recorded around 10:00 p.m., hovering through approximately 10:30. By about 10:50 the sky had become overcast and no object was visible, and heavy rain was recorded shortly after 11:00 p.m. Gill's source material includes sketches and a witness-signature sheet associated with the observation.",'facts':[('EVENT_START','6:45 p.m., 26 June 1959'),('INITIAL_OBSERVATION','Bright white light reported northwest of Boianai'),('APPROACH_DESCENT','Object reported approaching and descending; colour described as yellow/orange'),('REPORTED_OCCUPANTS','From about 6:55 p.m., witnesses reported figures moving on the object'),('LIGHT_EFFECT','Thin blue light or beam reported during figure appearances'),('CLOUD_ENTRY','Principal object reported entering cloud at about 7:20 p.m.'),('MULTIPLE_OBJECTS','Additional objects reported later overhead, over the sea and toward nearby villages'),('DEPARTURE_SEQUENCE','Around 9:30 p.m. larger object reportedly moved away toward Giwa while changing colour'),('LATE_REAPPEARANCE','Overhead object reported again around 10:00–10:30 p.m.'),('EVENT_END','By about 10:50 p.m. overcast conditions obscured the sky; heavy rain followed after 11:00 p.m.')]},
 {'id':'AU-NAA-CASE-BOIANAI-19590627','title':'Boianai reported signal exchange — 27 June 1959','pages':(208,209),'date':'1959-06-27','start':'18:00','observer':'William B. Gill and other Boianai witnesses','location':'Boianai, Territory of Papua and New Guinea','confidence':'HIGH','narrative':"On 27 June 1959 at Boianai, Annie Laurie was reported to have first noticed a large object at about 6:00 p.m. in approximately the same area as the previous night's principal object; William B. Gill recorded seeing it at about 6:02 p.m. Gill called other witnesses, and the group reported four figures on the upper portion of the object. The account says Gill and Ananias Rarata waved their arms and that figures on the object appeared to make corresponding gestures. Gill then directed long torch flashes toward the object; after a short interval the object was reported to make wavering motions. Repeated waving and flashing were followed by an apparent approach of the object for roughly half a minute before it stopped. The figures then disappeared from view, later reappearing, and a blue light was reported twice. By about 6:30 p.m. Gill went to dinner; at 7:00 the object was still reported present but appeared smaller. After an evening church service, cloud had covered the sky by about 7:45. At approximately 10:40 p.m. a loud explosive sound was heard near the mission house, but no object was seen in connection with it. A few drops of rain were recorded around 11:05 p.m.",'facts':[('EVENT_START','About 6:00 p.m., 27 June 1959'),('INITIAL_OBSERVATION','Large object reported in approximately the previous night’s position'),('REPORTED_OCCUPANTS','Four figures reported on the upper portion of the object'),('GESTURE_EXCHANGE','Witnesses reported waving and receiving apparently corresponding gestures'),('LIGHT_SIGNAL','Gill reported directing torch flashes toward the object'),('OBJECT_RESPONSE','Object reported making wavering motions and then approaching before stopping'),('REPORTED_OCCUPANTS_RETURN','Figures reportedly reappeared; blue light reported twice'),('LATE_VISIBILITY','Object still reported present at 7:00 p.m.; cloud covered sky by about 7:45 p.m.'),('LATE_SOUND','Loud explosive sound heard near mission house about 10:40 p.m.; no object seen with the sound'),('EVENT_END','A few drops of rain recorded around 11:05 p.m.')]},
 {'id':'AU-NAA-CASE-BOIANAI-19590628','title':'Boianai multiple-object observation — 28 June 1959','pages':(209,210),'date':'1959-06-28','start':'18:45','observer':'William B. Gill and other Boianai witnesses','location':'Boianai, Territory of Papua and New Guinea','confidence':'HIGH','narrative':"For 28 June 1959, the Boianai notes record no object at 6:00 p.m., followed by one very high object almost overhead at about 6:45 p.m., distinguishable because it appeared to hover. At about 7:30 it was reported farther toward the southern sky but still roughly overhead. Around 9:10 p.m. three objects were recorded in an almost straight line in a clear sky. At about 11:00 p.m. the observers recorded eight objects at once, the largest number they said they had yet seen together; one appeared relatively low, but no activity was reported other than occasional hovering. At approximately 11:20 p.m. a sharp metallic bang was heard on the mission-house roof. The source says no object was seen to roll down the roof and that four objects were then visible high in a circle around the station. At 11:30 p.m. Gill retired while objects were reportedly still visible. The following morning the roof was inspected and no apparent mark or dent was found.",'facts':[('PRE_EVENT_CHECK','No UFO reported at 6:00 p.m., 28 June 1959'),('EVENT_START','About 6:45 p.m., one high hovering object reported almost overhead'),('MOTION','By about 7:30 p.m. object reported farther south but still roughly overhead'),('MULTIPLE_OBJECTS','About 9:10 p.m., three objects reported in an almost straight line'),('PEAK_COUNT','About 11:00 p.m., eight objects reported visible at once'),('ROOF_SOUND','About 11:20 p.m., sharp metallic bang heard on mission-house roof'),('LATE_CONFIGURATION','Four high objects reported in a circle around the station after the sound'),('EVENT_END','At 11:30 p.m. observers retired while objects were reportedly still visible'),('NEXT_DAY_CHECK','Roof inspected next morning; no apparent mark or dent found')]},
 {'id':'AU-NAA-CASE-BOIANAI-19590706','title':'Gubanauna Point observation — 6 July 1959','pages':(210,211),'date':'1959-07-06','start':'20:40','observer':'David F. Murie (OCR reading) and other witnesses','location':'Near Gubanauna Point, Papua and New Guinea','confidence':'HIGH','narrative':"A source statement dated Monday, 6 July 1959 records that at about 8:40 p.m. the observer noticed a white glow through cloud northwest of his position, a few degrees above Gubanauna Point. The glow became a brilliant white spot, descended, and moved slightly south. Its brightness then faded to a glow and finally a faint glimmer. After about five minutes it brightened again and moved in an anticlockwise circular path, then continued farther south and lower until Gubanauna Point obscured it at about 9:00 p.m. Through binoculars the observer described it as orange and disk-shaped. The source states that Mrs. Murie, Rev. E. Dams, Rev. W. Gill and more than ten college men also observed the event. The OCR rendering of the signed observer name reads 'David F. Murie' and is retained as an unnormalized source reading pending name verification.",'facts':[('EVENT_START','About 8:40 p.m., 6 July 1959'),('INITIAL_OBSERVATION','White glow through cloud northwest above Gubanauna Point'),('BRIGHTEN_DESCEND','Glow reportedly became brilliant white, descended and moved slightly south'),('FADE','Brightness faded from glow to faint glimmer'),('REBRIGHTEN_MOTION','After about five minutes it brightened and moved anticlockwise in a circular path'),('FINAL_MOTION','Continued south and lower until obscured by Gubanauna Point about 9:00 p.m.'),('BINOCULAR_APPEARANCE','Through binoculars described as orange and disk-shaped'),('WITNESSES','Source names additional witnesses and more than ten college men')]},
]

def locate(root:Path,name:str)->Path:
 hits=list(root.rglob(name))
 if len(hits)!=1: raise RuntimeError(f'Expected one {name}; found {len(hits)}')
 return hits[0]
def sha_file(p:Path)->str:
 h=hashlib.sha256()
 with p.open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
 return h.hexdigest()
def page_rows(con,start,end):return con.execute('select page_number,text,text_sha256 from text_access_page where access_copy_id=3 and page_number between ? and ? order by page_number',(start,end)).fetchall()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--input-dir',required=True);ap.add_argument('--output-dir',required=True);a=ap.parse_args();src=locate(Path(a.input_dir),'AUSTRALIA_UFO_IMPORT_MODULE_v0.2.1.sqlite');out=Path(a.output_dir);shutil.rmtree(out,ignore_errors=True);out.mkdir(parents=True);db=out/'AUSTRALIA_UFO_IMPORT_MODULE_v0.2.2.sqlite';shutil.copyfile(src,db)
 con=sqlite3.connect(db);con.row_factory=sqlite3.Row;con.execute('pragma foreign_keys=on');con.executescript('CREATE TABLE case_chronological_narrative(candidate_id TEXT PRIMARY KEY REFERENCES case_candidate(candidate_id),narrative_status TEXT NOT NULL,narrative_text TEXT NOT NULL,reconstruction_basis TEXT NOT NULL,classification_status TEXT NOT NULL); CREATE TABLE manual_case_fact(fact_id INTEGER PRIMARY KEY,candidate_id TEXT NOT NULL REFERENCES case_candidate(candidate_id),sequence_no INTEGER NOT NULL,fact_role TEXT NOT NULL,fact_text TEXT NOT NULL,source_basis TEXT NOT NULL);')
 source_file=con.execute("select source_file_id from file_access_match where access_copy_id=3 and relationship='SAME_ARCHIVAL_FILE' order by match_id limit 1").fetchone();sf=int(source_file[0]) if source_file else None;url=con.execute('select url from text_access_copy where access_copy_id=3').fetchone()[0]
 for case in CASES:
  start,end=case['pages'];pages=page_rows(con,start,end);raw='\n\n[CONTINUATION PAGE]\n\n'.join((p['text'] or '') for p in pages);rawsha=hashlib.sha256(raw.encode()).hexdigest();con.execute('insert into case_candidate values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(case['id'],'CASE_EVENT',case['title'],'SOURCE_CANDIDATE','AUSTRALIA_NAA_RAAF',sf,3,start,end,url,'MANUAL_MULTI_EVENT_SPLIT',case['confidence'],'MULTI_EVENT_SOURCE_SPLIT',case['date'],case['observer'],case['location'],None,None,None,None,json.dumps([case['date']]),json.dumps([case['start']]),None,rawsha,raw))
  for p in pages:con.execute('insert into candidate_source_page values(?,?,?,?)',(case['id'],3,p['page_number'],p['text_sha256']))
  if sf is not None:
   op=con.execute("select p.discovery_entry_number,p.item_page_http_200,p.first_page_binary_reachable,o.official_recordsearch_item_url,o.official_recordsearch_view_url from source_file_official_probe p join official_probe_result o on o.discovery_entry_number=p.discovery_entry_number where p.source_file_id=?",(sf,)).fetchone()
   if op:con.execute('insert into candidate_official_provenance values(?,?,?,?,?,?,?)',(case['id'],sf,*tuple(op)))
  con.execute('insert into case_chronological_narrative values(?,?,?,?,?)',(case['id'],'SOURCE_RECONSTRUCTED_DRAFT',case['narrative'],'Manual chronological reconstruction from linked archived pages; all observations remain attributed to the source/witnesses.','CE_NOT_YET_ADJUDICATED'))
  for seq,(role,text) in enumerate(case['facts'],1):con.execute('insert into manual_case_fact(candidate_id,sequence_no,fact_role,fact_text,source_basis) values(?,?,?,?,?)',(case['id'],seq,role,text,f'copy 3 pages {start}-{end}'))
 parent='AU-NAA-CLUSTER-C03-P0203-0206'
 for cid in ('AU-NAA-CASE-BOIANAI-19590621','AU-NAA-CASE-BOIANAI-19590626'):con.execute('insert or ignore into cluster_case_link values(?,?,?)',(parent,cid,'SPLIT_EVENT_FROM_MULTI_EVENT_BLOCK'))
 con.commit();quick=con.execute('pragma integrity_check').fetchone()[0];fk=con.execute('pragma foreign_key_check').fetchall();summary={'status':'PASS' if quick=='ok' and not fk and con.execute("select count(*) from case_candidate where extraction_method='MANUAL_MULTI_EVENT_SPLIT'").fetchone()[0]==5 else 'FAIL','new_boianai_split_cases':5,'total_case_candidates':con.execute('select count(*) from case_candidate').fetchone()[0],'source_reconstructed_chronological_narratives':con.execute('select count(*) from case_chronological_narrative').fetchone()[0],'manual_chronology_facts':con.execute('select count(*) from manual_case_fact').fetchone()[0],'official_provenance_links':con.execute('select count(*) from candidate_official_provenance').fetchone()[0],'ce_classes_assigned':con.execute('select count(*) from case_candidate where encounter_class_candidate is not null').fetchone()[0],'policy':'Boianai multi-event material split only where the archived source provides a distinct chronological event sequence. Narratives are source-attributed reconstructions, not truth adjudications. CE classification remains unassigned pending separate UFO-spec review.','sqlite_integrity_check':quick,'foreign_key_violations':len(fk)};(out/'SUMMARY.json').write_text(json.dumps(summary,indent=2)+'\n')
 with (out/'BOIANAI_CASES.csv').open('w',newline='',encoding='utf-8') as f:rs=con.execute("select candidate_id,title,event_date_raw,observer_raw,location_raw,page_start,page_end,extraction_confidence from case_candidate where extraction_method='MANUAL_MULTI_EVENT_SPLIT' order by event_date_raw");w=csv.writer(f);w.writerow([d[0] for d in rs.description]);w.writerows(rs)
 with (out/'BOIANAI_NARRATIVES.csv').open('w',newline='',encoding='utf-8') as f:rs=con.execute('select * from case_chronological_narrative order by candidate_id');w=csv.writer(f);w.writerow([d[0] for d in rs.description]);w.writerows(rs)
 con.close();checks=[]
 for p in sorted(out.rglob('*')):
  if p.is_file() and p.name!='SHA256SUMS.txt':checks.append(f'{sha_file(p)}  {p.relative_to(out).as_posix()}')
 (out/'SHA256SUMS.txt').write_text('\n'.join(checks)+'\n');print(json.dumps(summary,indent=2))
 if summary['status']!='PASS':raise SystemExit(1)
if __name__=='__main__':main()
